# Generated by Django 5.0.6 on 2024-06-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
