# Generated by Django 5.0.6 on 2024-06-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_order_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='router',
            name='user',
        ),
    ]
